---
- hosts: vm01
  gather_facts: no
  vars:
    MAPDRIVE_USER: "{{ MAPDRIVE_USER }}"
    MAPDRIVE_SECRET: "{{ MAPDRIVE_SECRET }}"
  tasks:
    - name: Debug MAPDRIVE_SECRET
      debug:
        var: MAPDRIVE_SECRET

    - name: test powershell
      win_shell: |
        get-host
      register: result_get_host

    - name: display result_get_host
      debug:
        var: result_get_host

    # - name: add directory
    #   win_file:
    #     path: C:\apps
    #     state: directory

    # - name: Download the notepad++ installer
    #   win_get_url:
    #     url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.7.8/npp.8.7.8.Installer.x64.exe
    #     dest: C:\apps\npp.8.7.8.Installer.x64.exe
    #     force: true

    - name: Create mapped drive with credentials that do not persist on the next logon
      community.windows.win_mapped_drive:
        letter: Z
        path: \\vcloudlabdemo01scripts.file.core.windows.net\apps
        state: present
        username: localhost\vcloudlabdemo01scripts  #"{{ MAPDRIVE_USER }}" #localhost\vcloudlabdemo01scripts #'{{ ansible_user }}'
        password: kC3B9UoaZEPvWKsocOHvndUtl+5NLc8tJOKLkjliPvWoV7VJpa/6YnZJy1NjjWSRvnlWE86a0XW2+ASto99H0A== #"{{ MAPDRIVE_SECRET }}"

    - name: Install notepad++
      win_shell: |
        echo '{{ MAPDRIVE_USER }}' | Out-File -FilePath C:\test.txt -Encoding ascii
        $secpasswd = ConvertTo-SecureString '{{ MAPDRIVE_SECRET }}' -AsPlainText -Force
        $username = '{{ MAPDRIVE_USER }}'.Trim()
        $mycreds = New-Object System.Management.Automation.PSCredential ($username, $secpasswd)
        New-PSDrive -Name 'Z' -PSProvider FileSystem -Root '\\vcloudlabdemo01scripts.file.core.windows.net\apps' -Credential $mycreds
        Z:\npp.8.7.8.Installer.x64.exe /S 